# Generated by Django 3.2 on 2024-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='place Name')),
                ('cat', models.IntegerField(choices=[(1, 'spritual'), (2, 'Historical'), (3, 'adventure')], verbose_name='Category')),
                ('lc', models.IntegerField(choices=[(1, 'Rajasthan'), (2, 'Delhi'), (3, 'Gujrat'), (4, 'Maharastra')], verbose_name='locations')),
                ('cdetail', models.CharField(max_length=300, verbose_name='place Detail')),
                ('cimage', models.ImageField(upload_to='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
